# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-24 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoSession',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('bsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.Session')),
            ],
        ),
    ]
