# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-26 01:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('runner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NeuralSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sort_name', models.CharField(blank=True, default='sort', max_length=200)),
                ('kwik_filename', models.CharField(blank=True, default='exp.kwik', max_length=100)),
                ('kwx_filename', models.CharField(blank=True, default='exp.kwx', max_length=100)),
                ('fit_n2b0', models.FloatField(blank=True, null=True)),
                ('fit_n2b1', models.FloatField(blank=True, null=True)),
                ('fit_b2n0', models.FloatField(blank=True, null=True)),
                ('fit_b2n1', models.FloatField(blank=True, null=True)),
                ('bsession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='runner.Session')),
            ],
        ),
    ]
