# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-09 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neural_sessions', '0002_neuralsession_grand_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neuralsession',
            name='bsession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.Session'),
        ),
    ]
