# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-09 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_sessions', '0003_auto_20170109_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralsession',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
