# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-14 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_sessions', '0004_neuralsession_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralsession',
            name='adapter',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='neuralsession',
            name='channel_quality_notes',
            field=models.TextField(blank=True, help_text='Notes on quality of channels (artefacts, noise levels, good SUs, etc.'),
        ),
        migrations.AddField(
            model_name='neuralsession',
            name='data_directory',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='neuralsession',
            name='exclude_channels',
            field=models.CharField(blank=True, help_text='Comma separated list of broken channels (Sorted order)', max_length=100),
        ),
        migrations.AddField(
            model_name='neuralsession',
            name='manipulator_angle',
            field=models.FloatField(blank=True, help_text='Angle of the manipulator from vertical', null=True),
        ),
        migrations.AddField(
            model_name='neuralsession',
            name='z_final',
            field=models.FloatField(blank=True, help_text='Height of manipulator at final depth', null=True),
        ),
        migrations.AddField(
            model_name='neuralsession',
            name='z_touch',
            field=models.FloatField(blank=True, help_text='Height of manipulator at initial touch', null=True),
        ),
        migrations.AddField(
            model_name='neuralsession',
            name='z_withdraw',
            field=models.FloatField(blank=True, help_text='Height of manipulator at withdrawal', null=True),
        ),
        migrations.AlterField(
            model_name='neuralsession',
            name='kwik_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='neuralsession',
            name='kwx_filename',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='neuralsession',
            name='sort_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
