# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-16 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_sessions', '0006_auto_20171213_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralsession',
            name='electrode',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
