# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-19 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neural_sessions', '0007_neuralsession_electrode'),
    ]

    operations = [
        migrations.AddField(
            model_name='neuralsession',
            name='recording_numbers',
            field=models.CharField(blank=True, help_text='comma separated list of included recording numbers', max_length=20),
        ),
        migrations.AlterField(
            model_name='neuralsession',
            name='recording_number',
            field=models.IntegerField(blank=True, help_text='main recording number to analyze (deprecated)', null=True),
        ),
    ]
