# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-10 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0002_auto_20161206_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehaviorCage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('label_color', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='mouse',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mouse',
            name='genotype',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='mouse',
            name='headplate_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='mouse',
            name='in_training',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mouse',
            name='notes',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='mouse',
            name='sack_date',
            field=models.DateField(blank=True, null=True, verbose_name='sac date'),
        ),
        migrations.AddField(
            model_name='mouse',
            name='sex',
            field=models.IntegerField(choices=[(0, 'M'), (1, 'F'), (2, '?')], default=2),
        ),
        migrations.AddField(
            model_name='mouse',
            name='training_cohort',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mouse',
            name='training_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mouse',
            name='cage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.BehaviorCage'),
        ),
    ]
