# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0003_auto_20161209_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mouse',
            old_name='training_name',
            new_name='husbandry_name',
        ),
    ]
