# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-10 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0004_auto_20161210_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='max_rewards_per_trial',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='protocol_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='scheduler',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='script_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='step_first_rotation',
            field=models.IntegerField(blank=True, default=50, null=True),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='stimulus_set',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='mouse',
            name='timeout',
            field=models.IntegerField(blank=True, default=2000, null=True),
        ),
    ]
