# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-09 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neural_sessions', '0001_initial'),
        ('whisk_video', '0008_videosession_hide'),
        ('runner', '0006_optosession'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrandSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavioral_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.Session')),
                ('neural_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neural_sessions.NeuralSession')),
                ('opto_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.OptoSession')),
                ('video_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whisk_video.VideoSession')),
            ],
        ),
    ]
