# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-09 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0007_grandsession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandsession',
            name='behavioral_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.Session'),
        ),
        migrations.AlterField(
            model_name='grandsession',
            name='neural_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neural_sessions.NeuralSession'),
        ),
        migrations.AlterField(
            model_name='grandsession',
            name='opto_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.OptoSession'),
        ),
        migrations.AlterField(
            model_name='grandsession',
            name='video_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='whisk_video.VideoSession'),
        ),
    ]
