# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-09 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0008_auto_20170109_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grandsession',
            name='behavioral_session',
        ),
        migrations.RemoveField(
            model_name='grandsession',
            name='neural_session',
        ),
        migrations.RemoveField(
            model_name='grandsession',
            name='opto_session',
        ),
        migrations.RemoveField(
            model_name='grandsession',
            name='video_session',
        ),
        migrations.AddField(
            model_name='optosession',
            name='grand_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.GrandSession'),
        ),
        migrations.AddField(
            model_name='session',
            name='grand_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.GrandSession'),
        ),
    ]
