# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-09 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0009_auto_20170109_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='autosketch_path',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='logfile',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='mouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.Mouse'),
        ),
        migrations.AlterField(
            model_name='session',
            name='sandbox',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='session',
            name='script_path',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
