# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-09 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0011_auto_20170109_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
