# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-09 19:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0012_auto_20170109_1400'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grandsession',
            options={'ordering': ['-name']},
        ),
    ]
