# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-10 21:42
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('runner', '0013_auto_20170109_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='grandsession',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
