# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-10 21:56
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0014_grandsession_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandsession',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
