# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-16 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0015_auto_20170110_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='stepper_offset_steps',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
