# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-30 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0016_board_stepper_offset_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
