# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-06 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0017_mouse_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='task_reaction_time',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
