# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-04-10 23:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0019_auto_20170406_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='task_reaction_time',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
