# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-05-05 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0020_auto_20170410_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='nolick_max_wait_ms',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='mouse',
            name='nolick_required_interval_ms',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
