# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-03 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0022_mouse_use_ir_detector'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='target_water_volume',
            field=models.IntegerField(default=5000),
        ),
    ]
