# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-11 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0023_mouse_target_water_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='l_reward_sensitivity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='r_reward_sensitivity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
