# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-14 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0024_auto_20171210_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='optosession',
            name='position_notes',
            field=models.TextField(blank=True, help_text='Notes on position relative to brain or electrode'),
        ),
    ]
