# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-03-07 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0025_optosession_position_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='subprocess_window_xpos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
