# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-04-10 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0026_box_subprocess_window_xpos'),
    ]

    operations = [
        migrations.AddField(
            model_name='mouse',
            name='experimenter',
            field=models.IntegerField(blank=True, choices=[(0, 'chris'), (1, 'jung')], null=True),
        ),
    ]
