# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-12 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runner', '0028_auto_20180410_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouse',
            name='experimenter',
            field=models.IntegerField(choices=[(0, 'chris'), (1, 'jung'), (2, 'rikki')]),
        ),
    ]
