# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-24 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whiskvid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='all_edges_filename',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='videosession',
            name='bsession_logfilename',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='videosession',
            name='edge_summary_filename',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='videosession',
            name='fit_b2v0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='fit_b2v1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='fit_v2b0',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='fit_v2b1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='frame_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='frame_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='matfile_directory',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='videosession',
            name='monitor_video',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='videosession',
            name='param_edge_lumthresh',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='param_edge_x0',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='param_edge_x1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='param_edge_y0',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='param_edge_y1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='param_fol_x0',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='param_fol_x1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='param_fol_y0',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='param_fol_y1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='tac_filename',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='videosession',
            name='whiskers_table_filename',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
