# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 01:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whisk_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='frame_rate',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='bsession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runner.Session'),
        ),
    ]
