# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-28 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisk_video', '0002_auto_20161127_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='clustered_tac_filename',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='videosession',
            name='colorized_whisker_ends_filename',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='videosession',
            name='contacts_summary_filename',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
