# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisk_video', '0003_auto_20161128_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='colorized_contacts_summary_filename',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
