# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-29 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisk_video', '0004_videosession_colorized_contacts_summary_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='whisker_colors',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
