# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-04 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisk_video', '0005_videosession_whisker_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='param_edge_crop_x0',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='param_edge_crop_x1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='param_edge_crop_y0',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='param_edge_crop_y1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='param_edge_split_iters',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='param_face_side',
            field=models.IntegerField(blank=True, choices=[(0, 'left'), (1, 'right'), (2, 'top'), (3, 'bottom')], null=True),
        ),
    ]
