# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-12-06 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisk_video', '0006_auto_20161204_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='imaq_digital_gain',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='imaq_digital_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='imaq_exposure_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='lens_fstop',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='videosession',
            name='notes',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
