# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-04 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisk_video', '0007_auto_20161206_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='videosession',
            name='hide',
            field=models.BooleanField(default=False),
        ),
    ]
