# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-01-09 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisk_video', '0009_videosession_grand_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosession',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
