# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-30 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisk_video', '0010_auto_20170109_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosession',
            name='frame_height',
            field=models.IntegerField(blank=True, default=550, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='frame_rate',
            field=models.FloatField(blank=True, default=200.0, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='frame_width',
            field=models.IntegerField(blank=True, default=640, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='imaq_digital_gain',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='imaq_digital_offset',
            field=models.IntegerField(blank=True, default=-600, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='imaq_exposure_time',
            field=models.FloatField(blank=True, default=150.0, null=True),
        ),
        migrations.AlterField(
            model_name='videosession',
            name='lens_fstop',
            field=models.FloatField(blank=True, default=5.0, null=True),
        ),
    ]
