# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-12-14 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whisk_video', '0011_auto_20170330_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosession',
            name='lens_fstop',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
